[CmdletBinding()]
param()
$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$outputPath = Join-Path $projectRoot 'build/DynamicTraining.lua'
$modules = @('config', 'map_overlay', 'score_data', 'player', 'scoring', 'persistence', 'missions', 'intercept', 'sead_objective', 'sead', 'sead_sites', 'dead', 'recovery')
$variables = @{ config = 'Config'; map_overlay = 'MapOverlay'; score_data = 'ScoreData'; player = 'Player'; scoring = 'Scoring'; persistence = 'Persistence'; missions = 'Missions'; intercept = 'Intercept'; sead_objective = 'SEADObjective'; sead = 'SEAD'; sead_sites = 'SEADSites'; dead = 'DEAD'; recovery = 'Recovery' }
$builder = [System.Text.StringBuilder]::new()
[void]$builder.Append("-- Generated by scripts/Build-Mission.ps1. Edit src/*.lua instead.`n")
foreach ($module in $modules) {
    $moduleSource = [System.IO.File]::ReadAllText((Join-Path $projectRoot "src/$module.lua"))
    $variable = $variables[$module]
    [void]$builder.Append("local $variable = (function()`n")
    [void]$builder.Append($moduleSource.Replace("`r`n", "`n"))
    [void]$builder.Append("`nend)()`n`n")
}
[void]$builder.Append([System.IO.File]::ReadAllText((Join-Path $projectRoot 'src/DynamicTraining.lua')).Replace("`r`n", "`n"))
$bundle = $builder.ToString()
New-Item -ItemType Directory -Path (Split-Path -Parent $outputPath) -Force | Out-Null
if (-not (Test-Path -LiteralPath $outputPath) -or [System.IO.File]::ReadAllText($outputPath) -cne $bundle) {
    [System.IO.File]::WriteAllText($outputPath, $bundle, [System.Text.UTF8Encoding]::new($false))
}
