[CmdletBinding()]
param()
$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$outputPath = Join-Path $projectRoot 'build/DynamicTraining.lua'
# A single ordered map owns module order and bundle variable names.
$modules = [ordered]@{
    config = 'Config'; notifications = 'Notifications'; map_overlay = 'MapOverlay'
    score_data = 'ScoreData'; player = 'Player'; scoring = 'Scoring'; persistence = 'Persistence'
    missions = 'Missions'; training_zones = 'TrainingZones'; air_targets = 'AirTargets'; intercept = 'Intercept'; cap = 'CAP'
    sead_objective = 'SEADObjective'; sead = 'SEAD'; sead_sites = 'SEADSites'; dead = 'DEAD'
    recovery = 'Recovery'; mission_report = 'MissionReport'
}
$builder = [System.Text.StringBuilder]::new()
[void]$builder.Append("-- Generated by scripts/Build-Mission.ps1. Edit src/*.lua instead.`n")
foreach ($entry in $modules.GetEnumerator()) {
    $moduleSource = [System.IO.File]::ReadAllText((Join-Path $projectRoot "src/$($entry.Key).lua"))
    $variable = $entry.Value
    [void]$builder.Append("local $variable = (function()`n")
    [void]$builder.Append($moduleSource.Replace("`r`n", "`n"))
    [void]$builder.Append("`nend)()`n`n")
}
[void]$builder.Append([System.IO.File]::ReadAllText((Join-Path $projectRoot 'src/main.lua')).Replace("`r`n", "`n"))
$bundle = $builder.ToString()
New-Item -ItemType Directory -Path (Split-Path -Parent $outputPath) -Force | Out-Null
if (-not (Test-Path -LiteralPath $outputPath) -or [System.IO.File]::ReadAllText($outputPath) -cne $bundle) {
    [System.IO.File]::WriteAllText($outputPath, $bundle, [System.Text.UTF8Encoding]::new($false))
}
